name: Build Godot Android Plugin
description: Build Godot Android Plugin (standard or mono).
inputs:
  release_version:
    description: The Release Version of Build (standard/mono).
    default: "standard"

runs:
  using: "composite"
  steps:
    - name: Hello World
      shell: bash
      run: |
        echo Hello godot-android-action
